ci: move from drone ci to github actions
harvester/vm-dhcp-controller pull request #30
Opened 2024-04-24 08:52 UTC by starbops

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

We're going to transfer to GitHub Actions from Drone CI.

**Solution:**

Migrate pipelines originally defined in `.drone.yml` to GitHub Actions workflows.

Besides the CI migration, the golangci-lint version is bumped and added a timeout flag for execution.

**Related Issue:**

harvester/harvester#5327

**Test plan:**

2024-04-24 09:19 UTC, Yu-Jack commented on scripts/build
> +    GOARCH="$arch" CGO_ENABLED=0 GOARCH="$ARCH" go build -ldflags "-s -w $LINKFLAGS" -o bin/vm-dhcp-webhook-"$arch" ./cmd/webhook
duplicated

```suggestion
    GOARCH="$arch" CGO_ENABLED=0 go build -ldflags "-s -w $LINKFLAGS" -o bin/vm-dhcp-controller-"$arch" ./cmd/controller
    GOARCH="$arch" CGO_ENABLED=0 go build -ldflags "-s -w $LINKFLAGS" -o bin/vm-dhcp-agent-"$arch" ./cmd/agent
    GOARCH="$arch" CGO_ENABLED=0 go build -ldflags "-s -w $LINKFLAGS" -o bin/vm-dhcp-webhook-"$arch" ./cmd/webhook
```

2024-04-24 09:19 UTC, Yu-Jack commented on Dockerfile.dapper
> +    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.57.1; \
Should we remove `RUN if [ "${ARCH}" = "amd64" ]; then \`?

2024-04-24 09:51 UTC, bk201 commented on .github/workflows/main.yml
> +    - release/v**
no `release/v**` branches in this repo.

2024-04-24 10:08 UTC, Yu-Jack approved these changes
LGTM, thanks.

2024-04-24 11:36 UTC, starbops commented
The local build path using `make package` seems to be broken with a "file not found" error. We need to add the architecture suffix to the copy command. Please check again, thanks. cc @Yu-Jack

2024-04-25 01:04 UTC, Yu-Jack reviewed
After fixing that, run make build before running make package.

Since Dockerfile wil copy binaries for you, I think we don't need to co in package.

2024-04-25 01:04 UTC, Yu-Jack commented on scripts/package
> +cp bin/vm-dhcp-controller${SUFFIX} dist/artifacts/vm-dhcp-controller${SUFFIX}
you don't need to copy here, Dockerfile will do that for you.

2024-04-25 01:04 UTC, Yu-Jack commented on scripts/package-agent
> +cp bin/vm-dhcp-agent${SUFFIX} dist/artifacts/vm-dhcp-agent${SUFFIX}
same

2024-04-25 01:04 UTC, Yu-Jack commented on scripts/package-webhook
> +cp bin/vm-dhcp-webhook${SUFFIX} dist/artifacts/vm-dhcp-webhook${SUFFIX}
same

2024-04-25 01:05 UTC, Yu-Jack commented
One more question, do we need artifact here?

2024-04-25 02:07 UTC, starbops commented
> One more question, do we need artifact folder here?

It seems like a legacy to me. I removed them entirely from the package scripts. Thanks for the input!

2024-04-25 03:11 UTC, Yu-Jack requested changes

2024-04-25 03:11 UTC, Yu-Jack commented on scripts/package
> +./package-webhook
Miss `cd $(dirname $0)`

```suggestion
cd $(dirname $0)
./package-controller
./package-agent
./package-webhook
```

2024-04-25 05:25 UTC, bk201 approved these changes

2024-04-25 07:10 UTC, Yu-Jack approved these changes
LGTM, thanks!

2024-04-25 07:28 UTC, starbops commented
Waiting for rancherlabs/eio#2205. Please do not merge yet.

2024-04-25 14:05 UTC, merged